### ISSUE TITLE
z command stops working after running zsh as root

### ISSUE THREAD

**Issue by gshanbhag525** [agkozak/zsh-z#13]
After starting a shell with root and run some cd commands, z stops working when switching back to normal user.

To Reproduce
`$ sudo -s`
`$ cd /tmp`
`$ cd /usr`
`$ exit`
`$ z tmp`

Expected behavior
z should continue to work and current dir should be changed to /usr.

Screenshots or recordings

System:

- OS: macOS 10.14.6
- Zsh version 5.7.1 
- Terminal emulator [e.g. iTerm2]

> I used zsh-z from your repo instead of the ohmyzsh z plugin.
People using ohmyzsh z plugin had same issues here's the issue link .
https://github.com/ohmyzsh/ohmyzsh/issues/8463
Hope you can help in this.
I was not able to make it run in my user environment. So i went again into sudo mode and changed the ownership of .z directory to get back the z working for user environment .
`$chown username .z `

**Comment by agkozak** [comment]
We can definitely make it work.

Try putting

    ZSHZ_OWNER=yourusername

in your `.zshrc` and then run `sudo -s`. Try the same series of commands and see if it all works. Setting `ZSH_OWNER` causes `zsh-z` to `chown` your `.z` database file back to being yours -- otherwise, as you found out, it necessarily belongs to `root`, which is not desirable!

If for any reason that doesn't work, I'll have you do some experiments to see how `zsh` is loading as `root` in MacOS. I don't have a Mac to experiment with, but I'm sure we can resolve this problem easily.

**Comment by gshanbhag525** [comment]
it works, After putting this line in .zshrc.
`ZSHZ_OWNER=yourusername`.
The z works in both user and sudo env.

The setting up of the variable will work for rupa/z and omyzsh/z plugin too....Or is it just for your repo ?

**Comment by agkozak** [comment]
`ZSHZ_OWNER` only works for `zsh-z`, but `_Z_OWNER` should work for all three.
