### ISSUE TITLE
zshz:68: bad math expression: illegal character: ^[

### ISSUE THREAD

**Issue by nasyxx** [agkozak/zsh-z#17]
It seems there is something wrong with it.

```
λ z src
zshz:68: bad math expression: illegal character: ^[
```

```
λ zshz 
zshz:68: bad math expression: illegal character: ^[
2.75       /Users/Nasy/project
3.01       /Users/Nasy/.zinit/plugins/Aloxaf---fzf-tab/test
5.50       /Users/Nasy/src/pdm
6.86       /Users/Nasy/.zinit
11.03      /Users/Nasy/project/njit/multi-hop-qa/nsf_es_backend
56.68      /Users/Nasy/.config/nasy-emacs
67.55      /Users/Nasy/.zinit/plugins/Aloxaf---fzf-tab
135.97     /Users/Nasy/src/bat
```

**Comment by agkozak** [comment]
Could you post your `.zshrc`? I often find that is the best first step. Thanks.

**Comment by nasyxx** [comment]
Here is it:

https://gist.github.com/nasyxx/4d61483bb97c4e54bfc313000e40436b

**Comment by agkozak** [comment]
Thanks. Try commenting out or removing

    zinit ice wait"2"
    zinit light zpm-zsh/colors

Let me know if that fixes the problem. Then we can try to figure out what's really going wrong.

**Comment by nasyxx** [comment]
Hi, it fixed the problem.  Interesting.

**Comment by agkozak** [comment]
Give me a few more minutes and I'll have a fix for you.

**Comment by nasyxx** [comment]
Thank you very much!

**Comment by agkozak** [comment]
Try downloading the latest version. It should work for you.

**Comment by nasyxx** [comment]
Thanks!  It works!

**Comment by agkozak** [comment]
`zpm-zsh/colors` has a global variable `$c`, and the math expression `(( $+opts[-c] )) was being interpreted as having something to do with it. Because `colors` uses escape sequences, you were seeing error messages having to do with the Escape character, which is displayed as `^[`.

I replaced the math expression with a normal `[[...]]` test. It should do the same thing, and we won't have conflict.

Thank you for reporting this plugin conflict and thus helping to make ZSH-z better.
