### ISSUE TITLE
Common root logic is ignored

### ISSUE THREAD

**Issue by tekumara** [agkozak/zsh-z#23]
When there's a common root, z chooses the shortest matching directory as I expect:
```
$ cat ~/.z
/Users/tekumara/code/setup|1250.4200000000001|1593232602
/Users/tekumara/code|223.405|1593230323

$ z code -l
common:    /Users/tekumara/code
737.07     /Users/tekumara/code
5002.87    /Users/tekumara/code/setup
```

However, the common root logic isn't applied in the following case, which gives the surprising behaviour of choosing the more frequent directory:
```
$ cd ~/.vscode/extensions
$ cat ~/.z
/Users/tekumara/code/setup|1252.4200000000001|1593232621
/Users/tekumara/code|223.405|1593230323
/Users/tekumara/.vscode/extensions|1|1593232655

$ z code -l
7.98       /Users/tekumara/.vscode/extensions
733.93     /Users/tekumara/code
4983.06    /Users/tekumara/code/setup
```

I was still expecting `/Users/tekumara/code` to win, despite the addition of the vscode directory.

FYI: rupa/z has the [same behaviour](https://github.com/rupa/z/issues/289).

**Comment by agkozak** [comment]
You're quite right - that is the behavior of `rupa/z`, and since `zsh-z` is for the most part a drop-in replacement for `rupa/z`, the results should be the same.

The underlying reason is that in the second instance, where you're searching for `code` and the possible matches are

    /Users/tekumara/.vscode/extensions
    /Users/tekumara/code
    /Users/tekumara/code/setup

there is not really a common root. There would only be a common root if all the matches started with `/Users/tekumara/code`. The presence of a possible match that is not "common" means that the "common directory" logic does not apply.

I am working on an alternate way for `zsh-z` to pick out the best match in the `no-subdirectories` branch, which I encourage you to switch to and try out. [You can read about its development here](https://github.com/agkozak/zsh-z/issues/14), but the basic idea is that if the best match is `/Users/tekumara/code/setup` and you'd typed `z code`, you'd end up in `/Users/tekumara/code` -- the experimental code just drops any subdirectories of the best match that do not contain the search text in them. If you'd typed `z set`, then, and the best match had also been `/Users/tekumara/code/setup`, you'd end up in `/Users/tekumara/code/setup`, since `set` was what you were looking for.

The new behavior appears to work well, and I've got a number of people testing it out. If it continues to be a success, I'll merge it into the `master` branch as an alternative method that can be enabled by setting an environment variable. Try it and let me know what you think.

**Comment by agkozak** [comment]
Actually, I've decided that the new feature is mature enough to be on the `master` branch. So use that, but include

    ZSHZ_UNCOMMON=1

in your `.zshrc`.

**Comment by tekumara** [comment]
Thanks @agkozak I'm using `zsh-z.plugin.zsh` on master (0d1f65a) but don't see any differences in behaviour:

```
$ echo $ZSHZ_UNCOMMON
1

$ z code -l
7.91       /Users/tekumara/.vscode/extensions
150.49     /Users/tekumara/code
856.32     /Users/tekumara/code/setup
```

```
$ echo $ZSHZ_UNCOMMON


$ z code -l
7.91       /Users/tekumara/.vscode/extensions
150.49     /Users/tekumara/code
856.30     /Users/tekumara/code/setup
```

**Comment by agkozak** [comment]
The new, alternate behavior (when you set `ZSHZ_UNCOMMON=1`) doesn't change the ranking of the possible matches. It changes where you end up if you simply type `z code`.

In your example, if you set `ZSHZ_UNCOMMON=1` and type `z code`, ZSH-z picks the highest-ranking match (`Users/tekumara/code/setup`) and drops the `/setup` subdirectory (ZSH-z will keep dropping subdirectories until it arrives at the text you were actually searching for). So you end up in `/Users/tekumara/code`,

If you use the default "common prefix" method, well -- there is no common prefix. You only have a common prefix when *all* of the possible matches start with the same letters, and the presence of `/Users/tekumara/.vscode/extensions` in the database prevents that from happening. So there's no common directory to jump to, and ZSH-z simply sends you to the highest-ranking match: `/Users/tekumara/code/setup`.

**Comment by tekumara** [comment]
OIC thanks for helping me understand! I didn't realise the new logic was applied on top of the scoring.

So as you say, with `ZSHZ_UNCOMMON=1`, then `z code` takes me to `/Users/tekumara/code` as I'd like instead of `/Users/tekumara/code/setup`.
