### ISSUE TITLE
sudo zsh complains about insecure directories

### ISSUE THREAD

**Issue by kellytrinh** [agkozak/zsh-z#28]
Running under WSL

The original `z.sh` works fine and I use the `_Z_OWNER={username}` option to access z when using `sudo`

Installed `zsh-z.plugin.zsh` and working fine as normal user but when I do `sudo zsh` I get the following:

```
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]?
```

a 'y' proceeds seems to work fine but I am wondering what is causing problem and now to make the error go away

**Comment by agkozak** [comment]
This is a problem that is unrelated to ZSH-z, except insofar as ZSH-z uses `compinit` to do completions. Almost all completions in ZSH are done using `compinit`; you probably weren't using it before, because `z.sh` uses the now rare and very archaic `compsys` completion system.

This problem also pretty much only occurs on systems where the user's dotfiles are loaded in administrative mode (Ubuntu does this, I know -- many other OSes don't). The idea is that while it is convenient to load your own `.zshrc` when you type `sudo -s`, it's a bit insecure. You're loading, with root privileges, scripts that belong to a regular user. In this case, it is most likely completion scripts like ZSH-z's `_zshz` file. So, on these particular operating systems, ZSH asks if you really want to run all of those possibly risky scripts.

If you want to make the yes/no prompt go away, you can find the line in your `.zshrc` that says

    autoload -U compinit && compinit

and instead type

    autoload -U compinit && compinit -i
